### ISSUE TITLE
Site unreachable

### ISSUE THREAD

**Issue by MedaiP90** [dougrich/tokenerator#104]
The site [tokens.dougrich.net](https://tokens.dougrich.net/editor) is currently unreachable (I'm from Italy), i wonder if is this intentional or not?

**Comment by DwarfSun** [comment]
Also unreachable from South Africa.

**Comment by Ruiji98** [comment]
> The site [tokens.dougrich.net](https://tokens.dougrich.net/editor) is currently unreachable (I'm from Italy), i wonder if is this intentional or not?

I'm from Italy too and the site is still unreachable. Did you find what's happenig? I love that site for making tokens and used it since 4 years ago. If you guys will discover something please let me know it too

**Comment by MedaiP90** [comment]
@Ruiji98  it seems that the site is no longer online: *pinging* the address fails. The project is unmantained since 2 years ago, I think we wont see dougrich online soon. That wouldn't be a problem if building the docker image locally was possible, but it seems that a required file is missing from the repo ... :'(

**Comment by dougrich** [comment]
It is back up. Sorry for the delay.

@MedaiP90 - which file is missing?

**Comment by MedaiP90** [comment]
> It is back up. Sorry for the delay.
> 
> 
> 
> @MedaiP90 - which file is missing?

Thanks for the great news!!

The file missing is `ux/src/token-parts.js`

**Comment by dougrich** [comment]
@MedaiP90 this is the bundled token parts after they get built

you should run
```
cd tooling
npm start -- bundle
```
from the root of the project and it will drop out `ux/src/token-parts.js` as well as `api/src/token-parts.js`

I mention these steps in the README.md but mostly as a reminder to myself without any documentation - I should clear that up.

in addition there are cleaner/more obvious ways of doing this now then there were two years ago, so I'll try to fix this up soon.

**Comment by MedaiP90** [comment]
@dougrich thanks for the clarification
